config/routes.rb
Rails.application.routes.draw do
  resources :units
  resources :recipes
  resources :ingredients
  root 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :ingredientsRecipes, dependent: :restrict_with_error
    has_many :recipes, through: :ingredientsRecipes
    validates :name, presence: true
end

app/models/ingredients_recipe.rb
class IngredientsRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  belongs_to :unit

  validates :amount, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredientsRecipes, dependent: :destroy
    has_many :ingredients, through: :ingredientsRecipes
    accepts_nested_attributes_for :ingredientsRecipes, allow_destroy: true
    
    has_many :steps, dependent: :destroy
    accepts_nested_attributes_for :steps, allow_destroy: true
    validates_associated :steps

    validates :title, :total_time, :preparation_time, :serving, presence: true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe

  validates :description, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
    has_many :ingredientsRecipes
    validates :name, :symbol, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.order(:name)
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.order(:title).includes(:ingredients)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.ingredientsRecipes.build
    @recipe.steps.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :total_time, :preparation_time, :cooking_time, :serving, :description, :comment, ingredientsRecipes_attributes: [:id, :ingredient_id, :amount, :unit_id, :_destroy], steps_attributes: [:id, :recipe_id, :number, :description, :_destroy])
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.order(:name)
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :symbol)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def button_to_add_fields(name, f, association)
        new_object = f.object.send(association).klass.new
        id = new_object.object_id
        fields = f.fields_for(association, new_object, child_index: id) do |builder|
          render(association.to_s.singularize + "_fields", f: builder)
        end
                
        button_tag("Add", id: id, onclick: "addField(event)",  data: { fields: fields.gsub("\n", "") }, class: "action-btn add-btn") +
        button_tag("Remove", onclick: "removeField(event)", class: "action-btn")
      end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ingredient-header well">
    <div class="field">
      <strong><%= form.label :name, "Name:" %></strong>
      <%= form.text_field :name %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "action-btn" %>
    <%= link_to "Back", ingredients_path, class: "soft-btn" %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= link_to 'Show', ingredient, class: "soft-btn" %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient), class: "action-btn" %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' }, class: "danger-btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path, class: "action-btn" %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredient</h1>

<div class="ingredient-header well">
  <strong>Name:</strong>
  <%= @ingredient.name %>
</div>

<%= link_to 'Edit', edit_ingredient_path(@ingredient), class: "action-btn" %>
<%= link_to 'Back', ingredients_path, class: "soft-btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="top-bar">
    </div>
    <div class="header-container">
      <header>
        <div class="logo">Cooking App</div>
      </header>
    </div>
    <div class="nav-container">
      <nav>
        <ul>
          <li class="active"><%= link_to 'Home', recipes_path %></a></li>
          <li><%= link_to 'Recipes', recipes_path %></li>
          <li><%= link_to 'Ingredients', ingredients_path %></a></li>
          <li><%= link_to 'Units', units_path %></li>
        </ul>
      </nav>
    </div>
    <div class="subnav-container">
    </div>
    <main>
      <div class="content">
        <%= yield %>
      </div>
    </main>
  </body>
  <footer></footer> 
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="recipe-header">
    <div class="recipe-photo">
        <%# image_tag "default-recipe-2.jpg", alt: "Recipe picture" %>
    </div>
    <div class="recipe-info">
      <div class="field">
        <%= form.label :title, "Title:" %>
        <%= form.text_field :title %>
      </div>
      
      <div class="recipe-time">
        <div class="field total-time">
          <%= form.label :total_time, "Total time:" %>
          <%= form.number_field :total_time %> mins
        </div>
        
        <div class="field preparation-time">
          <%= form.label :preparation_time, "Preparation:" %>
          <%= form.number_field :preparation_time %> mins
        </div>

        <div class="field cooking-time">
          <%= form.label :cooking_time, "Cooking:" %>
          <%= form.number_field :cooking_time %> mins
        </div>
      </div>

      <div class="field">
        <%= form.label :serving, "Serving:" %>
        <%= form.number_field :serving %> persons
      </div>
    </div>
    <div class="recipe-description">
      <div class="field">
        <%= form.label :description, "Description:" %>
        <%= form.text_area :description, :rows => 5 %>
      </div>
    </div>
    <!--
      <div class="field">
        <%# form.label :comment %>
        <%# form.text_area :comment %>
      </div>
    -->
  </div>
  
  <br />

  <div id="ingredientList" class="dynamic-list">
    <div class="dynamic-list-header">
      <%= label "ingredients", "Ingredients: " %>
    </div>
    <div class="dynamic-list-buttons">
      <%= button_to_add_fields "Add", form, :ingredientsRecipes %>
    </div>
    <div class="dynamic-list-content">
      <%= form.fields_for :ingredientsRecipes do |builder| %>
        <%= render 'ingredientsRecipe_fields', :f => builder %>
      <% end %>
    </div>
  </div>

  <div id="stepList" class="dynamic-list">
    <div class="dynamic-list-header">
      <%= label "steps", "Steps: " %>
    </div>
    <div class="dynamic-list-buttons">
      <%= button_to_add_fields "Add", form, :steps %>
    </div>
    <div class="dynamic-list-content">
      <%= form.fields_for :steps do |builder| %>
        <%= render 'step_fields', :f => builder %>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "action-btn" %>
    <%= link_to "Back", recipes_path, class: "soft-btn" %>
  </div>
<% end %>

app/views/recipes/_ingredientsRecipe_fields.html.erb
<div class="dynamic-list-element ingredient">
    <span>:</span>
    <%# f.label :name, "Ingredient : " %>
    <%= f.collection_select :ingredient_id, Ingredient.order(:name), :id, :name, {:prompt => true} %>
    <%= f.label :amount, "Amount :" %>
    <%= f.number_field :amount %>
    <%= f.collection_select :unit_id, Unit.order(:name), :id, :symbol, {:prompt => true} %>
    <%= f.hidden_field :_destroy if @recipe.persisted? %>
</div>

app/views/recipes/_step_fields.html.erb
<div class="dynamic-list-element step">
  <%# f.hidden_field :number, value: 1 %>
  <span>:</span>
  <%# f.label :description, "Description : " %>
  <%= f.text_area :description %>
  <%= f.hidden_field :_destroy if @recipe.persisted? %>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Time</th>
      <th>Ingredients</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.total_time %></td>
        <td><%= recipe.ingredients.map(&:name).join(', ') %></td>
        <td><%= link_to 'Show', recipe, class: "soft-btn" %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe), class: "action-btn" %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: "danger-btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path, class: "action-btn" %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="recipe-header">
    <div class="recipe-photo"><img src="Images/imageDefaut.jpg" alt="Recipe picture"></div>
    <div class="recipe-info">
      <div class="field">
        <strong><%= @recipe.title %></strong>
      </div>
      
      <div class="recipe-time">
        <div class="field total-time">
          <strong>Total time:</strong>
          <%= @recipe.total_time %> mins
        </div>
        
        <div class="field preparation-time">
          <strong>Preparation time:</strong>
          <%= @recipe.preparation_time %> mins
        </div>

        <div class="field cooking-time">
          <strong>Cooking time:</strong>
          <%= @recipe.cooking_time %> mins
        </div>
      </div>

      <div class="field">
        <strong>Serving:</strong>
        <%= @recipe.serving %>
      </div>
    </div>
    <div class="recipe-description">
      <div class="field">
        <strong>Description:</strong>
        <%= @recipe.description %>
      </div>
    </div>
  </div>
  
  <br />

  <div id="ingredientList" class="dynamic-list">
    <div class="dynamic-list-header">
      <%= label "ingredients", "Ingredients: " %>
    </div>
    <div class="dynamic-list-buttons">
      
    </div>
    <div class="dynamic-list-content">
      <% @recipe.ingredientsRecipes.each do |portion| %>
      - <%= "#{portion.ingredient.name} : #{ portion.amount.to_s + portion.unit.symbol}" %><br/>
      <% end %>
    </div>
  </div>

  <div id="stepList" class="dynamic-list">
    <div class="dynamic-list-header">
      <%= label "steps", "Steps: " %>
    </div>
    <div class="dynamic-list-buttons">
      
    </div>
    <div class="dynamic-list-content">
      <% @recipe.steps.each do |step| %>
      - <%= "#{ step.description}" %><br/>
      <% end %>
    </div>
  </div>

<!--<p>
  <strong>Comment:</strong>
  <%# @recipe.comment %>
</p>-->


<%= link_to 'Edit', edit_recipe_path(@recipe), class: "action-btn" %>
<%= link_to 'Back', recipes_path, class: "soft-btn" %>

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="unit-header well">
    <div class="field">
      <strong><%= form.label :name, "Name:" %></strong>
      <%= form.text_field :name %>
    </div>
    <div class="field">
      <strong><%= form.label :symbol, "Symbol:" %></strong>
      <%= form.text_field :symbol %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "action-btn" %>
    <%= link_to "Back", units_path, class: "soft-btn" %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.symbol %></td>
        <td><%= link_to 'Show', unit, class: "soft-btn" %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit), class: "action-btn" %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' }, class: "danger-btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path, class: "action-btn" %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Unit</h1>

<div class="unit-header well">
  <div class="field">
    <strong>Name:</strong>
    <%= @unit.name %>
  </div>

  <div class="field">
    <strong>Symbol:</strong>
    <%= @unit.symbol %>
  </div>
</div>

<%= link_to 'Edit', edit_unit_path(@unit), class: "action-btn" %>
<%= link_to 'Back', units_path, class: "soft-btn" %>